#!/bin/bash

ACCOUNT=$1

notmuch new
logger -t offlineimap -p mail.info "Sync of mail account completed"
NEWDIRS=$(ls ~/Mails/$ACCOUNT/INBOX/new/ | wc -l)
if [ ! "$NEWDIRS" -eq "0" ]; then
  terminal-notifier -title "New Mails" -subtitle ${ACCOUNT} -message "$NEWDIRS" -appIcon ~/.mutt/mutt.icns
fi
