# vi:ft=ruby
cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/versions'
brew 'mas'

# mutt
tap 'tgray/homebrew-tgbrew'
brew 'muttqt'
brew 'contacts2'
brew 'offlineimap'
brew 'urlview'
brew 'msmtp'
brew 'notmuch'
brew 'terminal-notifier'
brew 'w3m'
brew 'mutt'

# neovim
tap 'neovim/homebrew-neovim'
tap 'universal-ctags/universal-ctags'
brew 'neovim'
brew 'universal-ctags'

# apps
cask '1password'
cask 'appcleaner'
cask 'dropbox'
cask 'firefox'
cask 'genymotion'
cask 'github-desktop'
cask 'google-chrome'
cask 'java'
cask 'paw'
cask 'slack'
cask 'soapui'
cask 'sourcetree'
cask 'sparkleshare'
cask 'tunnelblick'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
cask 'vmware-fusion'
cask 'qlstephen'
cask 'google-cloud-sdk'
mas 'Baby Monitor 3G', id: 626137367
mas 'Keynote', id: 409183694
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Pixelmator', id: 407963104
mas 'Tweetbot', id: 557168941
mas 'Xcode', id: 497799835
mas 'iA Writer', id: 775737590

# tools
brew 'diff-so-fancy'
brew 'fzf'
brew 'go'
brew 'graphviz'
brew 'heroku'
brew 'icu4c'
brew 'imagemagick'
brew 'influxdb'
brew 'ledger'
brew 'mtr'
brew 'nmap'
brew 'phantomjs'
brew 'pstree'
brew 'qt55'
brew 'rbenv'
brew 'nodenv'
brew 'reattach-to-user-namespace'
brew 'task'
brew 'watchman'
brew 'xz'
brew 'zsh'
brew 'jq'
brew 'kubectl'
brew 'kubernetes-helm'
brew 'redis'
brew 'watch'

# services
brew 'elasticsearch', restart_service: :changed, start_service: true
brew 'postgresql94', restart_service: :changed, start_service: true
brew 'dnsmasq', restart_service: :changed, start_service: true
brew 'rabbitmq', restart_service: :changed, start_service: true
brew 'nginx', restart_service: :changed, start_service: true
brew 'syncthing', restart_service: :changed, start_service: true
